-- 코드를 입력하세요
SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, TO_CHAR(REPLY.CREATED_DATE, 'YYYY-MM-DD')
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_REPLY REPLY
  ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE >= DATE '2022-10-01'
AND BOARD.CREATED_DATE < DATE '2022-11-01'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;